Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -15,8 +15,8 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
         
-      - name: Install Newman (Postman CLI) & HTML Reporter
-        run: npm install -g newman newman-reporter-htmlextra
+      - name: Install Newman (Postman CLI), HTML Reporter & HTML Merger
+        run: npm install -g newman newman-reporter-htmlextra html-merger
                 
       - name: Install Chromedriver
         run: npm install -g chromedriver --detect_chromedriver_version
@@ -42,21 +42,36 @@ jobs:
         run: curl -k https://mobileap-uat.aboitizpower.com
         
       - name: Run API Tests
-        run: newman run "QA TESTING Payment Channel Routes(Complete flow).postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "ChannelRouteSampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/merged-report.xml --reporter-htmlextra-export docs/merged-report.html &&
-             newman run "QA TESTING Payment Complete Flow.postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "sampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/merged-report.xml --reporter-htmlextra-export docs/merged-report.html || echo "Ignoring Newman errors"
+        run: newman run "QA TESTING Payment Channel Routes(Complete flow).postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "ChannelRouteSampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/report_PChannelRoute.xml --reporter-htmlextra-export docs/report_PChannelRoute.html &&
+             newman run "QA TESTING Payment Complete Flow.postman_collection.json" -e "UAT SO.postman_environment.json" --iteration-data "sampleData.json" --suppress-exit-code --reporters cli,junit,htmlextra --reporter-junit-export docs/report_PCompleteFlow.xml --reporter-htmlextra-export docs/report_PCompleteFlow.html || echo "Ignoring Newman errors"
       
-      - name: Upload API Test Report
+      - name: Upload API Test report_PChannelRoute
         uses: actions/upload-artifact@v4
         with:
           name: api-test-report
           path: docs/report_PChannelRoute.xml
 
-      - name: Upload API Test HMTL Report
+      - name: Upload API Test report_PChannelRoute
         uses: actions/upload-artifact@v4
         with:
           name: api-test-report-html
-          path: docs/merged-report.html
+          path: docs/report_PChannelRoute.html
 
+      - name: Upload API Test report_PChannelRoute
+        uses: actions/upload-artifact@v4
+        with:
+          name: report_PCompleteFlow
+          path: docs/report_PCompleteFlow.xml
+
+      - name: Upload API Test report_PChannelRoute
+        uses: actions/upload-artifact@v4
+        with:
+          name: report_PCompleteFlow-html
+          path: docs/report_PCompleteFlow.html
+      
+      - name: Merge Html Report
+        run: html-merger -i docs/report_PChannelRoute.html docs/report_PCompleteFlow.html -o docs/merged-report.html
+        
       - name: Rename HTML Report File
         run: mv docs/merged-report.html docs/index.html
         
